export const PLACE_CATEGORIES = [
  'Restaurant',
  'Cafe',
  'Hotel',
  'Resort',
  'Beach',
  'Waterfall',
  'Hill Station',
  'Mountain',
  'Trekking',
  'Adventure Park',
  'Theme Park',
  'Amusement Park',
  'Wildlife Sanctuary',
  'National Park',
  'Zoo',
  'Museum',
  'Historical Place',
  'Heritage Site',
  'Temple',
  'Church',
  'Mosque',
  'Tourist Attraction',
  'Shopping',
  'Market',
  'Mall',
  'Homestay',
  'Camp',
  'Lake',
  'River',
  'Viewpoint',
  'Garden',
  'Park',
  'Other',
]

// Keep categories used by places created before the expanded list available for editing and filtering.
export const LEGACY_PLACE_CATEGORIES = ['Nature', 'Heritage', 'Adventure']
export const PLACE_CATEGORY_OPTIONS = [...PLACE_CATEGORIES, ...LEGACY_PLACE_CATEGORIES]
